package com.hrms;

import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

	public class insert extends javax.swing.JFrame {

	    /**
	     * Creates new form insert
	     */
	    public insert() {
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	    private void initComponents() {

	        jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        jLabel3 = new javax.swing.JLabel();
	        jLabel4 = new javax.swing.JLabel();
	        txtfirst = new javax.swing.JTextField();
	        txtlast = new javax.swing.JTextField();
	        txtname = new javax.swing.JTextField();
	        txtphone = new javax.swing.JTextField();
	        jButton1 = new javax.swing.JButton();
	        jScrollPane1 = new javax.swing.JScrollPane();
	        jTable1 = new javax.swing.JTable();
	        jButton2 = new javax.swing.JButton();
	        jButton3 = new javax.swing.JButton();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        setTitle("INSERT DATA");

	        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
	        jLabel1.setText("Last Name");

	        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
	        jLabel2.setText("Phone No");

	        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
	        jLabel3.setText("First Name");

	        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
	        jLabel4.setText("User Name");

	        txtfirst.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

	        txtlast.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

	        txtname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

	        txtphone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

	        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
	        jButton1.setText("INSERT");
	        jButton1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton1ActionPerformed(evt);
	            }
	        });

	        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
	        jTable1.setModel(new javax.swing.table.DefaultTableModel(
	            new Object [][] {

	            },
	            new String [] {
	                "First Name", "Last Name", "User Name", "Phone No"
	            }
	        ) {
	            Class[] types = new Class [] {
	                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
	            };

	            public Class getColumnClass(int columnIndex) {
	                return types [columnIndex];
	            }
	        });
	        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
	            public void mouseClicked(java.awt.event.MouseEvent evt) {
	                jTable1MouseClicked(evt);
	            }
	        });
	        jScrollPane1.setViewportView(jTable1);

	        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
	        jButton2.setText("DELETE");
	        jButton2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton2ActionPerformed(evt);
	            }
	        });

	        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
	        jButton3.setText("UPDATE");
	        jButton3.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton3ActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(37, 37, 37)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addGap(19, 19, 19)
	                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(26, 26, 26)
	                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
	                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                        .addGroup(layout.createSequentialGroup()
	                            .addComponent(jLabel2)
	                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGroup(layout.createSequentialGroup()
	                            .addComponent(jLabel4)
	                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                            .addComponent(jLabel1)
	                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(txtlast, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                            .addComponent(jLabel3)
	                            .addGap(70, 70, 70)
	                            .addComponent(txtfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGap(92, 92, 92)
	                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                .addGap(18, 18, 18)
	                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(30, Short.MAX_VALUE))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addContainerGap()
	                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGap(34, 34, 34)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(jLabel3)
	                            .addComponent(txtfirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGap(22, 22, 22)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(jLabel1)
	                            .addComponent(txtlast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGap(20, 20, 20)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(jLabel4)
	                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGap(25, 25, 25)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(jLabel2)
	                            .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGap(29, 29, 29)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGap(18, 18, 18)
	                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                .addContainerGap(20, Short.MAX_VALUE))
	        );

	        pack();
	        setLocationRelativeTo(null);
	    }// </editor-fold>//GEN-END:initComponents

	    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	        // TODO add your handling code here:
	        
	        DefaultTableModel data = (DefaultTableModel)jTable1.getModel();
	        data.addRow(new Object[]{
	            txtfirst.getText(),
	            txtlast.getText(),
	            txtname.getText(),
	            txtphone.getText(),
	        
	        });
	        txtfirst.setText("");
	        txtlast.setText("");
	        txtname.setText("");
	        txtphone.setText("");
	        
	        
	        // Code in the Description....
	        
	    }//GEN-LAST:event_jButton1ActionPerformed

	    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
	        // TODO add your handling code here:
	        DefaultTableModel delete = (DefaultTableModel)jTable1.getModel();
	        
	        if(jTable1.getSelectedRowCount() == 1)
	        {
	            delete.removeRow(jTable1.getSelectedRow());
	        }
	        else{
	            if(jTable1.getRowCount() == 0){
	                JOptionPane.showMessageDialog(this, "Table is Empty.");
	            }
	            else{
	                JOptionPane.showMessageDialog(this, "Please Select Single Row For Delete");
	            }
	        }
	        
	    }//GEN-LAST:event_jButton2ActionPerformed

	    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
	        // TODO add your handling code here:
	        int i = jTable1.getSelectedRow();
	         DefaultTableModel update = (DefaultTableModel)jTable1.getModel();
	         
	        if(i>=0){
	            update.setValueAt(txtfirst.getText(), i, 0);
	            update.setValueAt(txtlast.getText(), i, 1);
	            update.setValueAt(txtname.getText(), i, 2);
	            update.setValueAt(txtphone.getText(), i, 3);
	        }
	        else{
	            JOptionPane.showMessageDialog(null, "Error");
	        }
	    }//GEN-LAST:event_jButton3ActionPerformed

	    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
	        // TODO add your handling code here:
	        
	        
	        int selectedRow = jTable1.getSelectedRow();
	        DefaultTableModel update = (DefaultTableModel)jTable1.getModel();
	        
	        txtfirst.setText(update.getValueAt(selectedRow, 0).toString());
	        txtlast.setText(update.getValueAt(selectedRow, 1).toString());
	        txtname.setText(update.getValueAt(selectedRow, 2).toString());
	        txtphone.setText(update.getValueAt(selectedRow, 3).toString());
	    }//GEN-LAST:event_jTable1MouseClicked

	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new insert().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify//GEN-BEGIN:variables
	    private javax.swing.JButton jButton1;
	    private javax.swing.JButton jButton2;
	    private javax.swing.JButton jButton3;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JScrollPane jScrollPane1;
	    private javax.swing.JTable jTable1;
	    private javax.swing.JTextField txtfirst;
	    private javax.swing.JTextField txtlast;
	    private javax.swing.JTextField txtname;
	    private javax.swing.JTextField txtphone;
	    // End of variables declaration//GEN-END:variables
	

}
